version: '3.7'
services:
  web1:
    build: 
      context: ./app1
      dockerfile: Dockerfile
      args:
        foo: bar
        bar: foo
      labels:
        "com.example.description": "test"
      shm_size: "2gb"
    ports:
      - "5000:5000"
      - "5003:5000"
      - "5004:5000"
      - "5005:5000"
      - "5006:5000"
      - "5007:5000"
      - "5008:5000"
      - "5009:5000"
  web2:
    build: ./app2
    ports:
      - "5001:5000"
  web3:
    build: ./app3
    ports:
      - "5002:5000"
  redis:
    image: "redis:alpine"
